# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: homo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhomo.proto\"\xa2\x01\n\x14RegistrationResponse\x12\x10\n\x08strategy\x18\x01 \x01(\t\x12\x39\n\nparameters\x18\x02 \x03(\x0b\x32%.RegistrationResponse.ParametersEntry\x1a=\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.Parameter:\x02\x38\x01\"\xe9\x01\n\x0bUploadParam\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\x12\x30\n\nparameters\x18\x02 \x03(\x0b\x32\x1c.UploadParam.ParametersEntry\x12*\n\x07metrics\x18\x03 \x03(\x0b\x32\x19.UploadParam.MetricsEntry\x1a=\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.Parameter:\x02\x38\x01\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x86\x01\n\x0f\x41ggregateResult\x12\x34\n\nparameters\x18\x01 \x03(\x0b\x32 .AggregateResult.ParametersEntry\x1a=\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.Parameter:\x02\x38\x01\"*\n\tParameter\x12\x0e\n\x06values\x18\x01 \x03(\x01\x12\r\n\x05shape\x18\x02 \x03(\x05\"8\n\x10RegistrationInfo\x12\x12\n\nsample_num\x18\x01 \x01(\x05\x12\x10\n\x08step_num\x18\x02 \x01(\x05\x62\x06proto3')



_REGISTRATIONRESPONSE = DESCRIPTOR.message_types_by_name['RegistrationResponse']
_REGISTRATIONRESPONSE_PARAMETERSENTRY = _REGISTRATIONRESPONSE.nested_types_by_name['ParametersEntry']
_UPLOADPARAM = DESCRIPTOR.message_types_by_name['UploadParam']
_UPLOADPARAM_PARAMETERSENTRY = _UPLOADPARAM.nested_types_by_name['ParametersEntry']
_UPLOADPARAM_METRICSENTRY = _UPLOADPARAM.nested_types_by_name['MetricsEntry']
_AGGREGATERESULT = DESCRIPTOR.message_types_by_name['AggregateResult']
_AGGREGATERESULT_PARAMETERSENTRY = _AGGREGATERESULT.nested_types_by_name['ParametersEntry']
_PARAMETER = DESCRIPTOR.message_types_by_name['Parameter']
_REGISTRATIONINFO = DESCRIPTOR.message_types_by_name['RegistrationInfo']
RegistrationResponse = _reflection.GeneratedProtocolMessageType('RegistrationResponse', (_message.Message,), {

  'ParametersEntry' : _reflection.GeneratedProtocolMessageType('ParametersEntry', (_message.Message,), {
    'DESCRIPTOR' : _REGISTRATIONRESPONSE_PARAMETERSENTRY,
    '__module__' : 'homo_pb2'
    # @@protoc_insertion_point(class_scope:RegistrationResponse.ParametersEntry)
    })
  ,
  'DESCRIPTOR' : _REGISTRATIONRESPONSE,
  '__module__' : 'homo_pb2'
  # @@protoc_insertion_point(class_scope:RegistrationResponse)
  })
_sym_db.RegisterMessage(RegistrationResponse)
_sym_db.RegisterMessage(RegistrationResponse.ParametersEntry)

UploadParam = _reflection.GeneratedProtocolMessageType('UploadParam', (_message.Message,), {

  'ParametersEntry' : _reflection.GeneratedProtocolMessageType('ParametersEntry', (_message.Message,), {
    'DESCRIPTOR' : _UPLOADPARAM_PARAMETERSENTRY,
    '__module__' : 'homo_pb2'
    # @@protoc_insertion_point(class_scope:UploadParam.ParametersEntry)
    })
  ,

  'MetricsEntry' : _reflection.GeneratedProtocolMessageType('MetricsEntry', (_message.Message,), {
    'DESCRIPTOR' : _UPLOADPARAM_METRICSENTRY,
    '__module__' : 'homo_pb2'
    # @@protoc_insertion_point(class_scope:UploadParam.MetricsEntry)
    })
  ,
  'DESCRIPTOR' : _UPLOADPARAM,
  '__module__' : 'homo_pb2'
  # @@protoc_insertion_point(class_scope:UploadParam)
  })
_sym_db.RegisterMessage(UploadParam)
_sym_db.RegisterMessage(UploadParam.ParametersEntry)
_sym_db.RegisterMessage(UploadParam.MetricsEntry)

AggregateResult = _reflection.GeneratedProtocolMessageType('AggregateResult', (_message.Message,), {

  'ParametersEntry' : _reflection.GeneratedProtocolMessageType('ParametersEntry', (_message.Message,), {
    'DESCRIPTOR' : _AGGREGATERESULT_PARAMETERSENTRY,
    '__module__' : 'homo_pb2'
    # @@protoc_insertion_point(class_scope:AggregateResult.ParametersEntry)
    })
  ,
  'DESCRIPTOR' : _AGGREGATERESULT,
  '__module__' : 'homo_pb2'
  # @@protoc_insertion_point(class_scope:AggregateResult)
  })
_sym_db.RegisterMessage(AggregateResult)
_sym_db.RegisterMessage(AggregateResult.ParametersEntry)

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETER,
  '__module__' : 'homo_pb2'
  # @@protoc_insertion_point(class_scope:Parameter)
  })
_sym_db.RegisterMessage(Parameter)

RegistrationInfo = _reflection.GeneratedProtocolMessageType('RegistrationInfo', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONINFO,
  '__module__' : 'homo_pb2'
  # @@protoc_insertion_point(class_scope:RegistrationInfo)
  })
_sym_db.RegisterMessage(RegistrationInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTRATIONRESPONSE_PARAMETERSENTRY._options = None
  _REGISTRATIONRESPONSE_PARAMETERSENTRY._serialized_options = b'8\001'
  _UPLOADPARAM_PARAMETERSENTRY._options = None
  _UPLOADPARAM_PARAMETERSENTRY._serialized_options = b'8\001'
  _UPLOADPARAM_METRICSENTRY._options = None
  _UPLOADPARAM_METRICSENTRY._serialized_options = b'8\001'
  _AGGREGATERESULT_PARAMETERSENTRY._options = None
  _AGGREGATERESULT_PARAMETERSENTRY._serialized_options = b'8\001'
  _REGISTRATIONRESPONSE._serialized_start=15
  _REGISTRATIONRESPONSE._serialized_end=177
  _REGISTRATIONRESPONSE_PARAMETERSENTRY._serialized_start=116
  _REGISTRATIONRESPONSE_PARAMETERSENTRY._serialized_end=177
  _UPLOADPARAM._serialized_start=180
  _UPLOADPARAM._serialized_end=413
  _UPLOADPARAM_PARAMETERSENTRY._serialized_start=116
  _UPLOADPARAM_PARAMETERSENTRY._serialized_end=177
  _UPLOADPARAM_METRICSENTRY._serialized_start=367
  _UPLOADPARAM_METRICSENTRY._serialized_end=413
  _AGGREGATERESULT._serialized_start=416
  _AGGREGATERESULT._serialized_end=550
  _AGGREGATERESULT_PARAMETERSENTRY._serialized_start=116
  _AGGREGATERESULT_PARAMETERSENTRY._serialized_end=177
  _PARAMETER._serialized_start=552
  _PARAMETER._serialized_end=594
  _REGISTRATIONINFO._serialized_start=596
  _REGISTRATIONINFO._serialized_end=652
# @@protoc_insertion_point(module_scope)
