# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbase.proto\"=\n\x0b\x42\x61seRequest\x12\x12\n\nparty_name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"I\n\x0c\x42\x61seResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x32\x7f\n\x04\x42\x61se\x12%\n\x04send\x12\x0c.BaseRequest\x1a\r.BaseResponse\"\x00\x12%\n\x04post\x12\x0c.BaseRequest\x1a\r.BaseResponse\"\x00\x12)\n\x08\x63\x61llback\x12\x0c.BaseRequest\x1a\r.BaseResponse\"\x00\x62\x06proto3')



_BASEREQUEST = DESCRIPTOR.message_types_by_name['BaseRequest']
_BASERESPONSE = DESCRIPTOR.message_types_by_name['BaseResponse']
BaseRequest = _reflection.GeneratedProtocolMessageType('BaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _BASEREQUEST,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:BaseRequest)
  })
_sym_db.RegisterMessage(BaseRequest)

BaseResponse = _reflection.GeneratedProtocolMessageType('BaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _BASERESPONSE,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:BaseResponse)
  })
_sym_db.RegisterMessage(BaseResponse)

_BASE = DESCRIPTOR.services_by_name['Base']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BASEREQUEST._serialized_start=14
  _BASEREQUEST._serialized_end=75
  _BASERESPONSE._serialized_start=77
  _BASERESPONSE._serialized_end=150
  _BASE._serialized_start=152
  _BASE._serialized_end=279
# @@protoc_insertion_point(module_scope)
