# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: piss.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npiss.proto\x12\x07pissPKG\"!\n\x10RegistrationInfo\x12\r\n\x05route\x18\x01 \x01(\t\"\x1d\n\x08InitData\x12\x11\n\tdata_path\x18\x01 \x01(\t\"\xb3\x01\n\x12ParticipantsRoutes\x12\x37\n\x06routes\x18\x01 \x03(\x0b\x32\'.pissPKG.ParticipantsRoutes.RoutesEntry\x12\x17\n\x0finitiator_route\x18\x02 \x01(\t\x12\x1c\n\x14initiator_party_name\x18\x03 \x01(\t\x1a-\n\x0bRoutesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xab\x01\n\x14ShareEncryptionParam\x12L\n\x10\x65ncryption_param\x18\x01 \x03(\x0b\x32\x32.pissPKG.ShareEncryptionParam.EncryptionParamEntry\x12\r\n\x05route\x18\x02 \x01(\t\x1a\x36\n\x14\x45ncryptionParamEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x99\x02\n\x15ShareEncryptedSecrets\x12=\n\x08sub_keys\x18\x01 \x03(\x0b\x32+.pissPKG.ShareEncryptedSecrets.SubKeysEntry\x12\x44\n\x0b\x63ommitments\x18\x02 \x03(\x0b\x32/.pissPKG.ShareEncryptedSecrets.CommitmentsEntry\x12\x17\n\x0frecv_party_name\x18\x03 \x01(\t\x1a.\n\x0cSubKeysEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x32\n\x10\x43ommitmentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x80\x01\n\rSubSecretsSUM\x12<\n\x0csub_keys_sum\x18\x01 \x03(\x0b\x32&.pissPKG.SubSecretsSUM.SubKeysSumEntry\x1a\x31\n\x0fSubKeysSumEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\nSecretsSUM\x12\x13\n\x0bsecrets_sum\x18\x01 \x01(\t\"!\n\x08\x43\x61llBack\x12\x15\n\rcall_back_msg\x18\x01 \x01(\tb\x06proto3')



_REGISTRATIONINFO = DESCRIPTOR.message_types_by_name['RegistrationInfo']
_INITDATA = DESCRIPTOR.message_types_by_name['InitData']
_PARTICIPANTSROUTES = DESCRIPTOR.message_types_by_name['ParticipantsRoutes']
_PARTICIPANTSROUTES_ROUTESENTRY = _PARTICIPANTSROUTES.nested_types_by_name['RoutesEntry']
_SHAREENCRYPTIONPARAM = DESCRIPTOR.message_types_by_name['ShareEncryptionParam']
_SHAREENCRYPTIONPARAM_ENCRYPTIONPARAMENTRY = _SHAREENCRYPTIONPARAM.nested_types_by_name['EncryptionParamEntry']
_SHAREENCRYPTEDSECRETS = DESCRIPTOR.message_types_by_name['ShareEncryptedSecrets']
_SHAREENCRYPTEDSECRETS_SUBKEYSENTRY = _SHAREENCRYPTEDSECRETS.nested_types_by_name['SubKeysEntry']
_SHAREENCRYPTEDSECRETS_COMMITMENTSENTRY = _SHAREENCRYPTEDSECRETS.nested_types_by_name['CommitmentsEntry']
_SUBSECRETSSUM = DESCRIPTOR.message_types_by_name['SubSecretsSUM']
_SUBSECRETSSUM_SUBKEYSSUMENTRY = _SUBSECRETSSUM.nested_types_by_name['SubKeysSumEntry']
_SECRETSSUM = DESCRIPTOR.message_types_by_name['SecretsSUM']
_CALLBACK = DESCRIPTOR.message_types_by_name['CallBack']
RegistrationInfo = _reflection.GeneratedProtocolMessageType('RegistrationInfo', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONINFO,
  '__module__' : 'piss_pb2'
  # @@protoc_insertion_point(class_scope:pissPKG.RegistrationInfo)
  })
_sym_db.RegisterMessage(RegistrationInfo)

InitData = _reflection.GeneratedProtocolMessageType('InitData', (_message.Message,), {
  'DESCRIPTOR' : _INITDATA,
  '__module__' : 'piss_pb2'
  # @@protoc_insertion_point(class_scope:pissPKG.InitData)
  })
_sym_db.RegisterMessage(InitData)

ParticipantsRoutes = _reflection.GeneratedProtocolMessageType('ParticipantsRoutes', (_message.Message,), {

  'RoutesEntry' : _reflection.GeneratedProtocolMessageType('RoutesEntry', (_message.Message,), {
    'DESCRIPTOR' : _PARTICIPANTSROUTES_ROUTESENTRY,
    '__module__' : 'piss_pb2'
    # @@protoc_insertion_point(class_scope:pissPKG.ParticipantsRoutes.RoutesEntry)
    })
  ,
  'DESCRIPTOR' : _PARTICIPANTSROUTES,
  '__module__' : 'piss_pb2'
  # @@protoc_insertion_point(class_scope:pissPKG.ParticipantsRoutes)
  })
_sym_db.RegisterMessage(ParticipantsRoutes)
_sym_db.RegisterMessage(ParticipantsRoutes.RoutesEntry)

ShareEncryptionParam = _reflection.GeneratedProtocolMessageType('ShareEncryptionParam', (_message.Message,), {

  'EncryptionParamEntry' : _reflection.GeneratedProtocolMessageType('EncryptionParamEntry', (_message.Message,), {
    'DESCRIPTOR' : _SHAREENCRYPTIONPARAM_ENCRYPTIONPARAMENTRY,
    '__module__' : 'piss_pb2'
    # @@protoc_insertion_point(class_scope:pissPKG.ShareEncryptionParam.EncryptionParamEntry)
    })
  ,
  'DESCRIPTOR' : _SHAREENCRYPTIONPARAM,
  '__module__' : 'piss_pb2'
  # @@protoc_insertion_point(class_scope:pissPKG.ShareEncryptionParam)
  })
_sym_db.RegisterMessage(ShareEncryptionParam)
_sym_db.RegisterMessage(ShareEncryptionParam.EncryptionParamEntry)

ShareEncryptedSecrets = _reflection.GeneratedProtocolMessageType('ShareEncryptedSecrets', (_message.Message,), {

  'SubKeysEntry' : _reflection.GeneratedProtocolMessageType('SubKeysEntry', (_message.Message,), {
    'DESCRIPTOR' : _SHAREENCRYPTEDSECRETS_SUBKEYSENTRY,
    '__module__' : 'piss_pb2'
    # @@protoc_insertion_point(class_scope:pissPKG.ShareEncryptedSecrets.SubKeysEntry)
    })
  ,

  'CommitmentsEntry' : _reflection.GeneratedProtocolMessageType('CommitmentsEntry', (_message.Message,), {
    'DESCRIPTOR' : _SHAREENCRYPTEDSECRETS_COMMITMENTSENTRY,
    '__module__' : 'piss_pb2'
    # @@protoc_insertion_point(class_scope:pissPKG.ShareEncryptedSecrets.CommitmentsEntry)
    })
  ,
  'DESCRIPTOR' : _SHAREENCRYPTEDSECRETS,
  '__module__' : 'piss_pb2'
  # @@protoc_insertion_point(class_scope:pissPKG.ShareEncryptedSecrets)
  })
_sym_db.RegisterMessage(ShareEncryptedSecrets)
_sym_db.RegisterMessage(ShareEncryptedSecrets.SubKeysEntry)
_sym_db.RegisterMessage(ShareEncryptedSecrets.CommitmentsEntry)

SubSecretsSUM = _reflection.GeneratedProtocolMessageType('SubSecretsSUM', (_message.Message,), {

  'SubKeysSumEntry' : _reflection.GeneratedProtocolMessageType('SubKeysSumEntry', (_message.Message,), {
    'DESCRIPTOR' : _SUBSECRETSSUM_SUBKEYSSUMENTRY,
    '__module__' : 'piss_pb2'
    # @@protoc_insertion_point(class_scope:pissPKG.SubSecretsSUM.SubKeysSumEntry)
    })
  ,
  'DESCRIPTOR' : _SUBSECRETSSUM,
  '__module__' : 'piss_pb2'
  # @@protoc_insertion_point(class_scope:pissPKG.SubSecretsSUM)
  })
_sym_db.RegisterMessage(SubSecretsSUM)
_sym_db.RegisterMessage(SubSecretsSUM.SubKeysSumEntry)

SecretsSUM = _reflection.GeneratedProtocolMessageType('SecretsSUM', (_message.Message,), {
  'DESCRIPTOR' : _SECRETSSUM,
  '__module__' : 'piss_pb2'
  # @@protoc_insertion_point(class_scope:pissPKG.SecretsSUM)
  })
_sym_db.RegisterMessage(SecretsSUM)

CallBack = _reflection.GeneratedProtocolMessageType('CallBack', (_message.Message,), {
  'DESCRIPTOR' : _CALLBACK,
  '__module__' : 'piss_pb2'
  # @@protoc_insertion_point(class_scope:pissPKG.CallBack)
  })
_sym_db.RegisterMessage(CallBack)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARTICIPANTSROUTES_ROUTESENTRY._options = None
  _PARTICIPANTSROUTES_ROUTESENTRY._serialized_options = b'8\001'
  _SHAREENCRYPTIONPARAM_ENCRYPTIONPARAMENTRY._options = None
  _SHAREENCRYPTIONPARAM_ENCRYPTIONPARAMENTRY._serialized_options = b'8\001'
  _SHAREENCRYPTEDSECRETS_SUBKEYSENTRY._options = None
  _SHAREENCRYPTEDSECRETS_SUBKEYSENTRY._serialized_options = b'8\001'
  _SHAREENCRYPTEDSECRETS_COMMITMENTSENTRY._options = None
  _SHAREENCRYPTEDSECRETS_COMMITMENTSENTRY._serialized_options = b'8\001'
  _SUBSECRETSSUM_SUBKEYSSUMENTRY._options = None
  _SUBSECRETSSUM_SUBKEYSSUMENTRY._serialized_options = b'8\001'
  _REGISTRATIONINFO._serialized_start=23
  _REGISTRATIONINFO._serialized_end=56
  _INITDATA._serialized_start=58
  _INITDATA._serialized_end=87
  _PARTICIPANTSROUTES._serialized_start=90
  _PARTICIPANTSROUTES._serialized_end=269
  _PARTICIPANTSROUTES_ROUTESENTRY._serialized_start=224
  _PARTICIPANTSROUTES_ROUTESENTRY._serialized_end=269
  _SHAREENCRYPTIONPARAM._serialized_start=272
  _SHAREENCRYPTIONPARAM._serialized_end=443
  _SHAREENCRYPTIONPARAM_ENCRYPTIONPARAMENTRY._serialized_start=389
  _SHAREENCRYPTIONPARAM_ENCRYPTIONPARAMENTRY._serialized_end=443
  _SHAREENCRYPTEDSECRETS._serialized_start=446
  _SHAREENCRYPTEDSECRETS._serialized_end=727
  _SHAREENCRYPTEDSECRETS_SUBKEYSENTRY._serialized_start=629
  _SHAREENCRYPTEDSECRETS_SUBKEYSENTRY._serialized_end=675
  _SHAREENCRYPTEDSECRETS_COMMITMENTSENTRY._serialized_start=677
  _SHAREENCRYPTEDSECRETS_COMMITMENTSENTRY._serialized_end=727
  _SUBSECRETSSUM._serialized_start=730
  _SUBSECRETSSUM._serialized_end=858
  _SUBSECRETSSUM_SUBKEYSSUMENTRY._serialized_start=809
  _SUBSECRETSSUM_SUBKEYSSUMENTRY._serialized_end=858
  _SECRETSSUM._serialized_start=860
  _SECRETSSUM._serialized_end=893
  _CALLBACK._serialized_start=895
  _CALLBACK._serialized_end=928
# @@protoc_insertion_point(module_scope)
